defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
title: Jonathan Browne
author: Jonathan Browne
jbanalytics: https://analytics.jonathanb.dev
exclude: ["Gemfile", "Gemfile.lock", "*.sh", "README.md", "assets/3rdparty/README.txt"]