defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
gems:
 - jekyll-paginate
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title