defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
kramdown:
  header_offset: 1
title: jbyoshi.github.io
author: Jonathan Browne